#!/usr/bin/env python3
"""CI entry point for B1 independent four-dimensional metric curvature checks.

The imported conversation artifact is retained byte-for-byte under research/.
No R-series module is imported. Evidence is committed, not generated by another
CI shard. Numerical checks do not certify a complete gravity theory.
"""
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from research.auxiliary_volume_B1.verify_geometry import main

if __name__ == "__main__":
    main()
