#!/usr/bin/env python3
"""Map the two-vector benchmark to generalized-Proca building blocks.

Define X = -W^2/2.

Up to a boundary term,

    G_{mu nu} W^mu W^nu

is the quartic generalized-Proca structure generated by a term G4(X) linear
in X.  The remaining pieces correspond to G3(X) linear in X and G2(X)
quadratic in X.

This script also checks the background vector components in diagonal static
coordinates and shows that at least one regular-branch vector necessarily has
a nonzero longitudinal component at a horizon.
"""

from __future__ import annotations

import sympy as sp


r, M, q, ell = sp.symbols(
    "r M q ell", positive=True, finite=True
)
X = sp.symbols("X")


def gp_functions(sign=1):
    """Dimensionless interaction functions inside +/- ell^2 L[W].

    Overall normalization and ell^2 are kept outside.
    """
    G2 = sign * 24 * X**2
    G3 = sign * (-16) * X
    beta4 = sign * 4
    return G2, G3, beta4


def regular_profiles():
    D = r**3 + 2 * q * ell**2
    f = sp.factor(1 - 2 * M * r**2 / D)

    a = sp.factor(
        (r - r * f - q / 2) / (2 * r**2)
    )
    b = sp.factor(
        (r - r * f + q / 2) / (2 * r**2)
    )
    return f, a, b


def diagonal_components(profile, f):
    """In dv = dt + dr/f:
       W = profile dv = profile dt + profile/f dr.
    """
    Wt = sp.factor(profile)
    Wr = sp.factor(profile / f)
    norm = sp.simplify(
        -Wt**2 / f + f * Wr**2
    )
    return Wt, Wr, norm


def main():
    G2A, G3A, beta4A = gp_functions(+1)
    G2B, G3B, beta4B = gp_functions(-1)

    assert G2A == 24 * X**2
    assert G3A == -16 * X
    assert beta4A == 4
    assert G2B == -24 * X**2
    assert G3B == 16 * X
    assert beta4B == -4

    f, a, b = regular_profiles()

    At, Ar, A2 = diagonal_components(a, f)
    Bt, Br, B2 = diagonal_components(b, f)

    assert A2 == 0
    assert B2 == 0

    # A horizon is any positive root f(r_h)=0.  Let rh be abstract and use
    # only the horizon condition to evaluate the EF profile values.
    rh = sp.symbols("r_h", positive=True, finite=True)

    ah = sp.factor(
        (rh - q / 2) / (2 * rh**2)
    )
    bh = sp.factor(
        (rh + q / 2) / (2 * rh**2)
    )

    # For q>0 and rh>0, b_h is strictly positive.
    assert sp.simplify(
        bh - (2 * rh + q) / (4 * rh**2)
    ) == 0

    # Both horizon profile values cannot vanish simultaneously.
    simultaneous_sum = sp.factor(ah + bh)
    assert sp.simplify(
        simultaneous_sum - 1 / rh
    ) == 0

    # Fully extremal horizon.
    rh_ext = sp.Rational(4, 3) * M
    ah_ext = sp.factor(ah.subs(rh, rh_ext))
    bh_ext = sp.factor(bh.subs(rh, rh_ext))

    # Special q that makes A_t vanish at the extremal horizon.
    q_A_zero = sp.solve(
        sp.Eq(ah_ext, 0), q
    )[0]
    assert sp.simplify(
        q_A_zero - sp.Rational(8, 3) * M
    ) == 0

    # But B_t remains nonzero at that point.
    bh_when_a_zero = sp.simplify(
        bh_ext.subs(q, q_A_zero)
    )
    assert sp.simplify(
        bh_when_a_zero - sp.Rational(3, 4) / M
    ) == 0

    print("== Generalized-Proca mapping ==")
    print("A sector (apart from ell^2):")
    print(f"G2(X) = {G2A}")
    print(f"G3(X) = {G3A}")
    print(f"linear G4 coefficient beta4 = {beta4A}")
    print()
    print("B sector has the opposite signs:")
    print(f"G2(X) = {G2B}")
    print(f"G3(X) = {G3B}")
    print(f"linear G4 coefficient beta4 = {beta4B}")
    print()
    print("Both backgrounds have X=0 because W^2=0.")
    print("Nevertheless G4_X is nonzero.")
    print()

    print("== Static diagonal coordinates ==")
    print("dv = dt + dr/f")
    print(f"A_t = {At}")
    print(f"A_r = {Ar}")
    print(f"A^2 = {A2}")
    print(f"B_t = {Bt}")
    print(f"B_r = {Br}")
    print(f"B^2 = {B2}")
    print()
    print(
        "The radial/longitudinal component is nonzero whenever the EF "
        "profile is nonzero."
    )
    print()

    print("== Horizon profiles ==")
    print(f"a_h = {ah}")
    print(f"b_h = {bh}")
    print(f"a_h + b_h = {simultaneous_sum}")
    print(
        "For positive q and r_h, b_h is strictly positive; both vectors "
        "cannot simultaneously have vanishing longitudinal profiles."
    )
    print()

    print("== Fully extremal branch ==")
    print(f"r_h = {rh_ext}")
    print(f"a_h = {ah_ext}")
    print(f"b_h = {bh_ext}")
    print(f"q making a_h=0: {q_A_zero}")
    print(f"then b_h = {bh_when_a_zero}")
    print()
    print("All symbolic assertions passed.")


if __name__ == "__main__":
    main()
