#!/usr/bin/env python3
"""Heterotic Taub-NUT chronology twist: twisted currents and conformal weights.

Companion of heterotic_taubnut_twist_zero_modes.py (same conventions).

Part 1 (twisted current algebra, Step B of the phase-IV task): for the
right-moving matrix current Jbar = g^{-1} d_- g, the twist
    g1 -> g1 h(x^-),   h = exp(-lambda w x^- s3)
(which realizes g1(sigma+2pi) = g1(sigma) exp(2 pi lambda w s3)) gives
    Jbar -> h^{-1} Jbar h + h^{-1} d_- h.
Direct 2x2 algebra shows: the s3/2 component shifts by the constant
-2 lambda w, and the sigma_+/- components are multiplied by
exp(+-2 lambda w x^-).  Hence the mode labels of Jbar^{+-} shift by the
IMAGINARY amount alpha_w = +-2 i lambda w (hyperbolic flow), while the
same U(1)_B transformation acting on SU(2)_R shifts Kbar^{+-} modes by the
INTEGER +-2w (an inner automorphism of the affine su(2) algebra).

Part 2 (conformal weights, Steps C/D): in the abelian zero-mode sector
    L0^(i) = p_i^2 / (2 kappa_i)   (per chiral U(1) sector),
the large gauge transformation eps_B = 2 w sigma acts on matter and on the
Karabali-Schnitzer auxiliary bosons (holomorphic level matrix -K_L,
antiholomorphic level matrix -K_R; a single non-chiral auxiliary boson
exists iff K_L = K_R, which is the note's anomaly condition).  The total
L0 and Lbar0 shift by
    dL0    = 2 w (J^L_B + a^L_B),
    dLbar0 = 2 w (J^R_B + a^R_B),
i.e. by (flow) x (total gauge constraint); the w^2 terms cancel exactly
between matter and auxiliary sector.  Both shifts vanish on the constraint
surface.  Therefore L0^(w) = L0^(0) and Lbar0^(w) = Lbar0^(0) for every
physical state: the w-twisted representative and its untwisted
(Hopf-wound) gauge image have identical conformal weights and level
matching is inherited, not re-imposed.

Part 3 (Hopf-wound representative): the SU(2)_R affine spectral flow by
eta = 2w gives the exact formulas
    Kbar^3_0 -> Kbar^3_0 + k_2 w,   Lbar0 -> Lbar0 + 2 w Kbar^3_0 + k_2 w^2,
reproduced from the abelian zero-mode formula with kappa = k_2/2.  The
flowed vacuum has weight k_2 w^2 and Cartan charge k_2 w, which is the
weight of the extremal state (Kbar^+_{-1})^{k_2 w} |0> of the SAME
vacuum module; no new module is generated by even flow.

All checks are abelian zero-mode identities.  No statement about the
non-abelian SL(2,R) representation content, normalizability or the
no-ghost range is asserted.
"""

import sympy as sp

lam, delta, xm, sigma = sp.symbols("lambda delta x_minus sigma", real=True)
w = sp.Symbol("w", integer=True)
k1, k2 = sp.symbols("k_1 k_2", positive=True)
QA, PA, QB, PB = sp.symbols("Q_A P_A Q_B P_B", real=True)

# ---------------------------------------------------------------------------
# Part 1: transformation of the right-moving matrix current under the twist
# ---------------------------------------------------------------------------

s3 = sp.Matrix([[1, 0], [0, -1]])
sp_plus = sp.Matrix([[0, 1], [0, 0]])   # sigma_+ = (s1 + i s2)/2
sp_minus = sp.Matrix([[0, 0], [1, 0]])  # sigma_- = (s1 - i s2)/2

J3, Jp, Jm = sp.symbols("Jbar3 Jbar_plus Jbar_minus")
Jbar = J3 * s3 / 2 + Jp * sp_plus + Jm * sp_minus  # generic sl(2) element

h = sp.Matrix([[sp.exp(-lam * w * xm), 0], [0, sp.exp(lam * w * xm)]])  # exp(-lam w x^- s3)
# h realizes the monodromy g1(sigma+2pi) = g1(sigma) exp(2 pi lam w s3):
# x^- = tau - sigma decreases by 2 pi when sigma increases by 2 pi.
assert sp.simplify(h.subs(xm, xm - 2 * sp.pi) - h * sp.Matrix([[sp.exp(2 * sp.pi * lam * w), 0], [0, sp.exp(-2 * sp.pi * lam * w)]])) == sp.zeros(2, 2)

h_inv = h.inv()
Jbar_tw = sp.simplify(h_inv * Jbar * h + h_inv * sp.diff(h, xm))

# Decompose the twisted current in the same basis.
J3_tw = sp.simplify(Jbar_tw[0, 0] - Jbar_tw[1, 1])  # coefficient of s3/2
Jp_tw = sp.simplify(Jbar_tw[0, 1])
Jm_tw = sp.simplify(Jbar_tw[1, 0])
assert sp.simplify(J3_tw - (J3 - 2 * lam * w)) == 0
assert sp.simplify(Jp_tw - sp.exp(2 * lam * w * xm) * Jp) == 0
assert sp.simplify(Jm_tw - sp.exp(-2 * lam * w * xm) * Jm) == 0

# Mode expansion: exp(+-2 lam w x^-) sum_n J_n exp(-i n x^-)
#                 = sum_n J_n exp(-i (n +- 2 i lam w) x^-).
n = sp.Symbol("n", integer=True)
alpha_w = 2 * sp.I * lam * w
assert sp.simplify(sp.exp(2 * lam * w * xm) * sp.exp(-sp.I * n * xm) - sp.exp(-sp.I * (n + alpha_w) * xm)) == 0
assert sp.simplify(sp.exp(-2 * lam * w * xm) * sp.exp(-sp.I * n * xm) - sp.exp(-sp.I * (n - alpha_w) * xm)) == 0

# The same U(1)_B gauge transformation on SU(2)_R: h2 = exp(-i w x^- s3).
h2 = sp.Matrix([[sp.exp(-sp.I * w * xm), 0], [0, sp.exp(sp.I * w * xm)]])
K3, Kp, Km = sp.symbols("Kbar3 Kbar_plus Kbar_minus")
Kbar = K3 * s3 / 2 + Kp * sp_plus + Km * sp_minus
Kbar_tw = sp.simplify(h2.inv() * Kbar * h2 + h2.inv() * sp.diff(h2, xm))
assert sp.simplify((Kbar_tw[0, 0] - Kbar_tw[1, 1]) - (K3 - 2 * sp.I * w)) == 0
assert sp.simplify(Kbar_tw[0, 1] - sp.exp(2 * sp.I * w * xm) * Kp) == 0
# Integer mode shift: exp(2 i w x^-) exp(-i n x^-) = exp(-i (n - 2w) x^-).
assert sp.simplify(sp.exp(2 * sp.I * w * xm) * sp.exp(-sp.I * n * xm) - sp.exp(-sp.I * (n - 2 * w) * xm)) == 0
# and the SU(2) twist matrix is periodic (trivial monodromy) for integer w.
assert sp.simplify(h2.subs(xm, xm - 2 * sp.pi) - h2) == sp.zeros(2, 2)

print("Part 1: hyperbolic twist -> Jbar^3 shifts by -2 lam w, Jbar^{+-}_n -> Jbar^{+-}_{n +- 2 i lam w};")
print("        the same transformation on SU(2)_R is an integer flow Kbar^{+-}_n -> Kbar^{+-}_{n -+ 2w}.")

# ---------------------------------------------------------------------------
# Part 2: conformal weights in the abelian zero-mode sector
# ---------------------------------------------------------------------------

m, Mb, Nb, f1, f2, s1, s2 = sp.symbols("m Mbar Nbar f_1 f_2 s_1 s_2", real=True)
sectors = [
    ("SL2_L", "L", k1 / 2, 1, 0, m),
    ("FL1", "L", 1, QA, QB, s1),
    ("FL2", "L", 1, PA, PB, s2),
    ("SL2_R", "R", k1 / 2, delta, lam, Mb),
    ("SU2_R", "R", k2 / 2, 0, 1, Nb),
    ("FR1", "R", 1, delta, lam, f1),
    ("FR2", "R", 1, 0, 1, f2),
]


def level_matrix(chir):
    K = sp.zeros(2, 2)
    for (_, c, kap, qA, qB, _) in sectors:
        if c == chir:
            qv = sp.Matrix([qA, qB])
            K += kap * qv * qv.T
    return sp.simplify(K)


K_L = level_matrix("L")
K_R = level_matrix("R")
E_AA = -k1 * (1 - delta**2) - 2 * (QA**2 + PA**2 - delta**2)
E_AB = k1 * delta * lam - 2 * (QA * QB + PA * PB - delta * lam)
E_BB = k2 + k1 * lam**2 - 2 * (QB**2 + PB**2 - (1 + lam**2))

# Auxiliary bosons: zero modes a^L_X, a^R_X with holomorphic level matrix
# -K_L and antiholomorphic level matrix -K_R.  A single non-chiral boson
# requires K_L = K_R, i.e. the anomaly equations.
aL = sp.Matrix(sp.symbols("aL_A aL_B", real=True))
aR = sp.Matrix(sp.symbols("aR_A aR_B", real=True))
KL_inv = K_L.inv()
KR_inv = K_R.inv()


def matter_charge(chir, idx):
    return sp.expand(sum((qA, qB)[idx] * p for (_, c, kap, qA, qB, p) in sectors if c == chir))


JL = sp.Matrix([matter_charge("L", 0), matter_charge("L", 1)])
JR = sp.Matrix([matter_charge("R", 0), matter_charge("R", 1)])

# Abelian zero-mode Virasoro generators (Cartan/U(1) parts only).
L0_matter = sum(p**2 / (2 * kap) for (_, c, kap, _, _, p) in sectors if c == "L")
Lb0_matter = sum(p**2 / (2 * kap) for (_, c, kap, _, _, p) in sectors if c == "R")
L0_aux = -(aL.T * KL_inv * aL)[0, 0] / 2
Lb0_aux = -(aR.T * KR_inv * aR)[0, 0] / 2
L0 = L0_matter + L0_aux
Lb0 = Lb0_matter + Lb0_aux

# Flow: eps_B = 2 w sigma, eta = (0, 2w).
eta = sp.Matrix([0, 2 * w])
shift = {p: p + 2 * kap * qB * w for (_, c, kap, qA, qB, p) in sectors}
for i in range(2):
    shift[aL[i]] = aL[i] - (K_L * eta)[i]
    shift[aR[i]] = aR[i] - (K_R * eta)[i]

dL0 = sp.expand(L0.subs(shift, simultaneous=True) - L0)
dLb0 = sp.expand(Lb0.subs(shift, simultaneous=True) - Lb0)

CL = JL + aL  # total holomorphic zero-mode constraints
CR = JR + aR  # total antiholomorphic zero-mode constraints

# Exact identities: dL0 = 2w * C^L_B,  dLbar0 = 2w * C^R_B  (no w^2 remainder).
assert sp.simplify(dL0 - 2 * w * CL[1]) == 0
assert sp.simplify(dLb0 - 2 * w * CR[1]) == 0
# Matter-only w^2 terms are 2 w^2 (K_L)_BB and 2 w^2 (K_R)_BB; the auxiliary
# sector cancels them, and they agree with each other only on the anomaly surface.
dL0_matter = sp.expand(L0_matter.subs(shift, simultaneous=True) - L0_matter)
dLb0_matter = sp.expand(Lb0_matter.subs(shift, simultaneous=True) - Lb0_matter)
assert sp.simplify(dL0_matter - 2 * w * JL[1] - 2 * w**2 * K_L[1, 1]) == 0
assert sp.simplify(dLb0_matter - 2 * w * JR[1] - 2 * w**2 * K_R[1, 1]) == 0
assert sp.simplify(2 * (K_L - K_R)[1, 1] + E_BB) == 0
# Level matching of the matter part alone shifts by 2w (J^L_B - J^R_B) + w^2 (K_L - K_R)_BB ... 
# but with the auxiliary sector included the shift is 2w (C^L_B - C^R_B) = 0 on physical states.
assert sp.simplify((dL0 - dLb0) - 2 * w * (CL[1] - CR[1])) == 0
# On physical states (C = 0) both shifts vanish identically.
phys = {aL[0]: -JL[0], aL[1]: -JL[1], aR[0]: -JR[0], aR[1]: -JR[1]}
assert sp.simplify(dL0.subs(phys)) == 0
assert sp.simplify(dLb0.subs(phys)) == 0
print("Part 2: dL0 = 2w C^L_B and dLbar0 = 2w C^R_B exactly (w^2 terms cancel against the")
print("        auxiliary boson); both vanish on physical states -> L0^(w) = L0^(0), Lbar0^(w) = Lbar0^(0).")
print("        Level matching L0 - Lbar0 is inherited by the twisted representative.")

# ---------------------------------------------------------------------------
# Part 3: the Hopf-wound (untwisted) representative in SU(2)_R
# ---------------------------------------------------------------------------

# Abelian zero-mode formula with kappa = k_2/2, charge 1, eta = 2w:
Nb_flow = shift[Nb]
assert sp.simplify(Nb_flow - (Nb + k2 * w)) == 0
dLb0_su2 = sp.simplify(Nb_flow**2 / k2 - Nb**2 / k2)
assert sp.simplify(dLb0_su2 - (2 * w * Nb + k2 * w**2)) == 0
# Flowed vacuum: Cartan charge k_2 w, weight k_2 w^2 = weight of (K^+_{-1})^{k_2 w}|0>.
assert sp.simplify(dLb0_su2.subs(Nb, 0) - k2 * w**2) == 0
assert sp.simplify(sp.Abs(Nb_flow.subs(Nb, 0)) - k2 * sp.Abs(w)) == 0
print("Part 3: SU(2)_R flow by 2w: Kbar3_0 -> Kbar3_0 + k_2 w, Lbar0 -> Lbar0 + 2w Kbar3_0 + k_2 w^2;")
print("        flowed vacuum = extremal descendant of weight k_2 w^2 in the same module.")

print("OK: heterotic Taub-NUT twisted-current and level-matching checks passed.")
